// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package v1

import (
	"github.com/cicbyte/byte-code/api/v1"
)

type ControllerAuth struct{}

func NewAuth() v1.IV1Auth {
	return &ControllerAuth{}
}

type ControllerCategories struct{}

func NewCategories() v1.IV1Categories {
	return &ControllerCategories{}
}

type ControllerDashboard struct{}

func NewDashboard() v1.IV1Dashboard {
	return &ControllerDashboard{}
}

type ControllerHealth struct{}

func NewHealth() v1.IV1Health {
	return &ControllerHealth{}
}

type ControllerMenu struct{}

func NewMenu() v1.IV1Menu {
	return &ControllerMenu{}
}

type ControllerRole struct{}

func NewRole() v1.IV1Role {
	return &ControllerRole{}
}

type ControllerSetting struct{}

func NewSetting() v1.IV1Setting {
	return &ControllerSetting{}
}
